name: Deployment

concurrency: staging

on:
  workflow_dispatch:

jobs:
  test:
    uses: sergeimikhailov/motiv/.github/workflows/main.yml@main
    secrets:
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      GCP_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
      GCP_WORKLOAD_IDENTITY_SERVICE_ACCOUNT: ${{ secrets.GCP_WORKLOAD_IDENTITY_SERVICE_ACCOUNT }}
      GCP_CONFIGURATION_ANDROID_DEBUG: ${{ secrets.GCP_CONFIGURATION_ANDROID_DEBUG }}
      FIREBASE_APP_ID_DEBUG: ${{ secrets.FIREBASE_APP_ID_DEBUG }}

  deploy:
    needs: test
    runs-on: ubuntu-24.04
    environment: staging
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Gradle Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Firebase Config
        env:
          GCP_CONFIGURATION_ANDROID: ${{ secrets.GCP_CONFIGURATION_ANDROID }}
        working-directory: app
        run: echo $GCP_CONFIGURATION_ANDROID | base64 --decode > google-services.json

      - name: Build
        run: >-
          ./gradlew bundleRelease
          -Pandroid.injected.version.code=${GITHUB_RUN_NUMBER}
          -Pandroid.injected.version.name=v${GITHUB_RUN_NUMBER}-${GITHUB_SHA::7}

      - name: Sign
        uses: r0adkll/sign-android-release@349ebdef58775b1e0d8099458af0816dc79b6407 # v1
        with:
          releaseDirectory: app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.KEY_STORE }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Upload
        uses: r0adkll/upload-google-play@935ef9c68bb393a8e6116b1575626a7f5be3a7fb # v1.1.3
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: nz.mikhailov.motiv
          releaseFile: ${{ env.SIGNED_RELEASE_FILE }}
          track: internal
          mappingFile: app/build/outputs/mapping/release/mapping.txt

      - name: Create Release Tag
        uses: actions/github-script@v5
        with:
          github-token: ${{ github.token }}
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/release/v${{ github.run_number }}",
              sha: context.sha
            })
