name: Main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  workflow_call:
    secrets:
      GCP_CONFIGURATION_ANDROID_DEBUG:
        required: true

jobs:
  test:
    runs-on: ubuntu-24.04

    permissions:
      contents: read
      id-token: write

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: GCP Auth
        uses: google-github-actions/auth@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_WORKLOAD_IDENTITY_SERVICE_ACCOUNT }}

      - name: Setup Firebase CLI
        run: npm install --global firebase-tools

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Firebase Config
        env:
          GCP_CONFIGURATION_ANDROID_DEBUG: ${{ secrets.GCP_CONFIGURATION_ANDROID_DEBUG }}
        working-directory: app
        run: echo $GCP_CONFIGURATION_ANDROID_DEBUG | base64 --decode > google-services.json

      - name: Assemble Debug Build
        run: |
          ./gradlew assembleDebug \
            -Pandroid.injected.version.name=${GITHUB_SHA::7}

      - name: App Distribution
        run: |
          firebase appdistribution:distribute \
            ./app/build/outputs/apk/debug/app-debug.apk \
            --app ${{ secrets.FIREBASE_APP_ID_DEBUG }} \
            --test-case-ids-file ./test-case-ids.txt

      - name: Enable KVM group perms
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: run tests
        uses: reactivecircus/android-emulator-runner@1dcd009 # v2.34.0
        with:
          api-level: 29
          script: ./gradlew lint testDebug connectedDebugAndroidTest
