name: Main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  workflow_call:
    secrets:
      GCP_CONFIGURATION_ANDROID_DEBUG:
        required: true

jobs:
  test:
    runs-on: macos-13
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Firebase Config
        env:
          GCP_CONFIGURATION_ANDROID_DEBUG: ${{ secrets.GCP_CONFIGURATION_ANDROID_DEBUG }}
        working-directory: app
        run: echo $GCP_CONFIGURATION_ANDROID_DEBUG | base64 --decode > google-services.json

      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew lint testDebug connectedDebugAndroidTest
