name: Main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  workflow_call:
    secrets:
      GCP_CONFIGURATION_ANDROID_DEBUG:
        required: true

jobs:
  test:
    runs-on: macos-13

    permissions:
      contents: read
      id-token: write

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: GCP Auth
        uses: google-github-actions/auth@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Firebase Config
        env:
          GCP_CONFIGURATION_ANDROID_DEBUG: ${{ secrets.GCP_CONFIGURATION_ANDROID_DEBUG }}
        working-directory: app
        run: echo $GCP_CONFIGURATION_ANDROID_DEBUG | base64 --decode > google-services.json

      - name: App Distribution
        run: ./gradlew assembleDebug appDistributionUploadDebug --stacktrace

      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew lint testDebug connectedDebugAndroidTest
